name: FeatherQuill
settings:
  LINT_MODE: ${LINT_MODE}
packages:
  FeatherQuill:
    path: .
projectReferences:
    Demo:
      path: ./Demo/FeatureFlagsApp.xcodeproj
aggregateTargets:
  Lint:
    buildScripts:
      - path: Scripts/lint.sh
        name: Lint
        basedOnDependencyAnalysis: false
    schemes: {}